MVC_Net8/MVC_Net8/Models/ErrorViewModel.cs
namespace MVC_Net8.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC_Net8/MVC_Net8/Models/Lenguajes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Net8.Models
{
    public class Lenguajes
    {
        [Key]
        [Column("id")]
        public int id {get; set;}
        public string? nombre {get; set;}
        public DateTime? fecha {get; set;}
        public int? nivel {get;set;}
    }
}

MVC_Net8/MVC_Net8/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC_Net8.Models;

namespace MVC_Net8.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC_Net8/MVC_Net8/Controllers/LenguajesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MVC_Net8.Data;
using MVC_Net8.Models;

namespace MVC_Net8.Controllers
{
    [Route("lenguajes")]
    public class LenguajesController : Controller
    {
        private readonly ILogger<LenguajesController> _logger;
        private readonly AppDBContext _appDBContext;

        public LenguajesController(ILogger<LenguajesController> logger, AppDBContext appDBContext)
        {
            _logger = logger;
            _appDBContext = appDBContext;
        }

        [HttpGet]
        [Route("test")]
        public IActionResult Test(){
            return View();
        }

        [HttpGet]
        [Route("listado")]
        public async Task<IActionResult> Listado()
        {
            try
            {
                List<Lenguajes> lenguajes = await _appDBContext.lenguajes.ToListAsync();
                return View(lenguajes);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al obtener el listado de lenguajes.");
                return View("Error");
            }
        }
        [HttpGet]
        [Route("nuevo")]
        public IActionResult Nuevo(){
            return View();
        }


        [HttpPost]
        [Route("nuevo")]
        public async Task<IActionResult> Nuevo(Lenguajes lenguaje)
        {
            await _appDBContext.lenguajes.AddAsync(lenguaje);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Listado));
        }

        [HttpGet]
        [Route("editar")]
        public async Task<IActionResult> Editar(int id)
        {
            Lenguajes lenguaje = await _appDBContext.lenguajes.FirstAsync(l => l.id == id);
            
            return View(lenguaje);
        }

        [HttpPost]
        [Route("editar")]
        public async Task<IActionResult> Editar(Lenguajes lenguaje)
        {
            _appDBContext.lenguajes.Update(lenguaje);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Listado));
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            Lenguajes lenguaje = await _appDBContext.lenguajes.FirstAsync(l => l.id == id);
            _appDBContext.lenguajes.Remove(lenguaje);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Listado));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

MVC_Net8/MVC_Net8/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_Net8/MVC_Net8/Views/Lenguajes/Editar.cshtml
@model MVC_Net8.Models.Lenguajes
@{
    ViewData["Title"] = "Nuevo";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Lista Lenguajes</h2>
        <form asp-action="Editar" asp-controller="Lenguajes" method="post">
             <input type="hidden" asp-for="id">
            <div class="mb-3">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" asp-for="nombre">
            </div>

            <div class="mb-3">
                <label for="fecha">Fecha</label>
                <input type="date" class="form-control" asp-for="fecha">
            </div>

            <div class="mb-3">
                <label for="nivel">Nivel</label>
                <input type="number" class="form-control" asp-for="nivel" min="0" max="5">
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Guardar</button>
                <a asp-controller="Lenguajes" asp-action="Listado" class="btn btn-warning">Volver</a>
            </div>
        </form>
    </div>
</div>

MVC_Net8/MVC_Net8/Views/Lenguajes/Listado.cshtml
@model List<MVC_Net8.Models.Lenguajes>
@{
    ViewData["Title"] = "Listado";
}

<h1>@ViewData["Title"]</h1>


<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Lista Lenguajes</h2>
        <a asp-controller="Lenguajes" asp-action="Nuevo" class="btn btn-success mb-3">Nuevo</a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Fecha</th>
                    <th>Nivel</th>
                </tr>
            </thead>

            <tbody>
                @foreach(var leng in Model){
                    <tr>
                        <td>@leng.id</td>
                        <td>@leng.nombre</td>
                        <td>@(leng.fecha.HasValue ? leng.fecha.Value.ToString("dd/MM/yyyy") : "")</td>
                        <td>@leng.nivel</td>
                        <td>
                            <a asp-controller="Lenguajes" asp-action="Editar" asp-route-id="@leng.id" class="btn btn-primary mb-3">Editar</a>
                            <a asp-controller="Lenguajes" asp-action="Eliminar" asp-route-id="@leng.id" onclick="return confirmar()" class="btn btn-danger mb-3">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>

</div>

@section Scripts{
    <script>
        function confirmar(){
            return confirm("Estas seguro de eliminar?")
        }
    </script>
}

MVC_Net8/MVC_Net8/Views/Lenguajes/Nuevo.cshtml
@model MVC_Net8.Models.Lenguajes
@{
    ViewData["Title"] = "Nuevo";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Lista Lenguajes</h2>
        <form asp-action="Nuevo" asp-controller="Lenguajes" method="post">
            <div class="mb-3">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" asp-for="nombre">
            </div>

            <div class="mb-3">
                <label for="fecha">Fecha</label>
                <input type="date" class="form-control" asp-for="fecha">
            </div>

            <div class="mb-3">
                <label for="nivel">Nivel</label>
                <input type="number" class="form-control" asp-for="nivel" min="0" max="5">
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Guardar</button>
                <a asp-controller="Lenguajes" asp-action="Listado" class="btn btn-warning">Volver</a>
            </div>
        </form>
    </div>
</div>

MVC_Net8/MVC_Net8/Views/Lenguajes/Test.cshtml
@model MVC_Net8.Views.Lenguajes.Test
@{
    ViewData["Title"] = "Test";
}

<h1>@ViewData["Title"]</h1>

<div>
    
</div>

MVC_Net8/MVC_Net8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Net8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Net8.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Net8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_Net8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>